//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touchin_Grass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dangerous_Plant
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
