//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touchin_Grass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeinHausgartenEntities1 : DbContext
    {
        public MeinHausgartenEntities1()
            : base("name=MeinHausgartenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Cat> Cat { get; set; }
        public virtual DbSet<Dangerous_Plant> Dangerous_Plant { get; set; }
        public virtual DbSet<Plant> Plant { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
