//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touchin_Grass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Category { get; set; }
        public string Picture { get; set; }
        public string MoreInfo { get; set; }
        public string Place { get; set; }
        public string Recipe { get; set; }
        public Nullable<bool> is_poisonous { get; set; }
    
        public virtual Cat Cat { get; set; }
    }
}
